CREATE DATABASE clinic_db;

\c clinic_db;

CREATE TABLE PATIENTS (
    ID SERIAL PRIMARY KEY, 
    NAME TEXT, 
    DOB DATE, 
);

CREATE TABLE MEDICAL_HISTORIES (
  ID SERIAL PRIMARY KEY,
  ADMITTED_AT TIMESTAMP,
  STATUS VARCHAR(50),
  PATIENT_ID INT REFERENCES patients(ID)
);

CREATE TABLE INVOICE_ITEMS (
  ID SERIAL PRIMARY KEY,
  UNIT_PRICE DECIMAL,
  QUANTITY INT,
  TOTAL_PRICE DECIMAL,
  INVOICE_ID INT REFERENCES INVOICES(ID),
  TREATMENT_ID INT REFERENCES TREATMENTS(ID)
);

CREATE TABLE INVOICES (
  ID SERIAL PRIMARY KEY,
  TOTAL_AMOUNT DECIMAL,
  GENERATED_AT TIMESTAMP,
  PAYED_AT TIMESTAMP,
  MEDICAL_HISTORY_ID INT REFERENCES MEDICAL_HISTORIES(ID)
);

CREATE TABLE TREATMENTS (
  ID SERIAL PRIMARY KEY,
  TYPE VARCHAR(100),
  NAME VARCHAR(100)
);