CREATE DATABASE clinic_db;

\c clinic_db;

CREATE TABLE PATIENTS (
    ID SERIAL PRIMARY KEY, 
    NAME TEXT, 
    DOB DATE, 
);

CREATE TABLE MEDICAL_HISTORIES (
  ID SERIAL PRIMARY KEY,
  ADMITTED_AT TIMESTAMP,
  STATUS VARCHAR(50),
  PATIENT_ID INT REFERENCES patients(ID)
);

CREATE TABLE INVOICE_ITEMS (
  ID SERIAL PRIMARY KEY,
  UNIT_PRICE DECIMAL,
  QUANTITY INT,
  TOTAL_PRICE DECIMAL,
  INVOICE_ID INT REFERENCES INVOICES(ID),
  TREATMENT_ID INT REFERENCES TREATMENTS(ID)
);

CREATE TABLE INVOICES (
  ID SERIAL PRIMARY KEY,
  TOTAL_AMOUNT DECIMAL,
  GENERATED_AT TIMESTAMP,
  PAYED_AT TIMESTAMP,
  MEDICAL_HISTORY_ID INT REFERENCES MEDICAL_HISTORIES(ID)
);

CREATE TABLE TREATMENTS (
  ID SERIAL PRIMARY KEY,
  TYPE VARCHAR(100),
  NAME VARCHAR(100)
);

CREATE TABLE MEDICAL_HISTORIES_TREATMENTS (
  TREATMENT_ID INT REFERENCES TREATMENTS(ID),
  MEDICAL_HISTORY_ID INT REFERENCES MEDICAL_HISTORIES(ID),
  PRIMARY KEY (TREATMENT_ID, MEDICAL_HISTORY_ID)
);

CREATE INDEX PATIENT_ID_INDEX ON MEDICAL_HISTORIES(PATIENT_ID);
CREATE INDEX INVOICE_ID_INDEX ON INVOICE_ITEMS(INVOICE_ID);
CREATE INDEX TREATMENT_ID_INDEX ON INVOICE_ITEMS(TREATMENT_ID);
CREATE INDEX MEDICAL_HISTORY_ID_INDEX ON INVOICES(MEDICAL_HISTORY_ID);
CREATE INDEX TREATMENT_ID_INDEX ON MEDICAL_HISTORIES_TREATMENTS(TREATMENT_ID);
CREATE INDEX MEDICAL_HISTORY_ID_INDEX ON MEDICAL_HISTORIES_TREATMENTS(MEDICAL_HISTORY_ID);
