CREATE DATABASE clinic_db;

\c clinic_db;

CREATE TABLE PATIENTS (
    ID SERIAL PRIMARY KEY, 
    NAME TEXT, 
    DOB DATE, 
);

CREATE TABLE MEDICAL_HISTORIES (
  ID SERIAL PRIMARY KEY,
  ADMITTED_AT TIMESTAMP,
  STATUS VARCHAR(50),
  PATIENT_ID INT REFERENCES patients(ID)
);

CREATE TABLE INVOICE_ITEMS (
  ID SERIAL PRIMARY KEY,
  UNIT_PRICE DECIMAL,
  QUANTITY INT,
  TOTAL_PRICE DECIMAL,
  INVOICE_ID INT REFERENCES INVOICES(ID),
  TREATMENT_ID INT REFERENCES TREATMENTS(ID)
);